name: Build chat app with websocket

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  main:
    name: Build client

    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello world"
  
 